services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: CUSTOMER_ONBOARDING
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      API_URL: http://host.docker.internal:8080/v3/api-docs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MH_STORAGE: memory

volumes:
  postgres_data: